package OOPS;

public class Car {

    private String doors;
    private String engine;
    private int speed;

    /*
       Constructor: Constructor is a method which has a same class name with no return type. It will be useful to initialise the properties.
       Constructor will be automatically called at the time of object creation.
     */
    public Car(){
        doors = "opened";
        engine="not started";
        speed = 0;
    }

    /*
        We can overload the constructor which receives arguments while creating the object
     */

    public Car(String doors, String engine, int speed) {
        this.doors = doors;
        this.engine = engine;
        this.speed = speed;
    }
//    // Getters and Setters:
//
//    // Setters are methods which sets the values to the properties
//    public void setDoors(String doors){
//        /*
//           Actually the doors parameter and the property doors are same. So the method setDoors will get confused with the
//           parameter doors and property doors. We need to explicitly tell the method that property door is different .
//           To do this we use this keyword which points to the class.
//         */
//         this.doors = doors;
//    }
//
//    //Getters are methods used to get the value of the property
//
//    public String getDoors(){
//        return doors;
//    }
//
    // Actually setters and getters are generated by IDE itself by  selecting the properties and right click, select generate and click getters and setter

    public String getDoors() {
        return doors;
    }

    public void setDoors(String doors) {
        this.doors = doors;
    }

    public String getEngine() {
        return engine;
    }

    public void setEngine(String engine) {
        this.engine = engine;
    }

    public int getSpeed() {
        return speed;
    }

    public void setSpeed(int speed) {
        this.speed = speed;
    }

    public String run() {
    /*
       To run the car the doors to be closed, engine should be turned on, and speed should be > 0
     */
        if (doors.equals("closed") && engine.equals("on") && speed > 0) {
            return "Car will run";
        } else {
            return "Doors needs to be closed and engine should be turned on and speed should be >0";
        }
    }
}
